# LambDynamicLights configuration.
# The dynamic lights mode
mode = "fancy"

# Light sources settings.
[light_sources]
	# Enables water-sensitive light sources check. This means that water-sensitive items will not light up when submerged in water.
	water_sensitive_check = true
	# Enable block entities light source.
	block_entities = true
	# Enable entities light source.
	entities = true
	# Enable first-person player light source.
	self = true
	# TNT lighting mode. May be off, simple or fancy.
	tnt = "off"
	# Creeper lighting mode. May be off, simple or fancy.
	creeper = "simple"

	[light_sources.settings]

		[light_sources.settings.entities]

			[light_sources.settings.entities.minecraft]
				chicken = true
				panda = true
				bee = true
				axolotl = true
				arrow = true
				trader_llama = true
				donkey = true
				cow = true
				chest_minecart = true
				tropical_fish = true
				fox = true
				pig = true
				skeleton = true
				iron_golem = true
				bat = true
				frog = true
				rabbit = true
				cat = true
				zombie = true
				armor_stand = true
				sheep = true
				experience_orb = true
				player = true
				dolphin = true
				item = true
				potion = true
				turtle = true
				villager = true
				wolf = true
				salmon = true
				wandering_trader = true
				fishing_bobber = true
				zombie_villager = true
				polar_bear = true
				strider = true
				horse = true
				painting = true
				glow_squid = true
				cod = true
				glow_item_frame = false
				squid = true
				spider = true
				parrot = true
				creeper = true
				lightning_bolt = true
				enderman = true

			[light_sources.settings.entities.cobgyms]
				trainer_villager = true

			[light_sources.settings.entities.myloot]
				loot_chest_minecart = true

			[light_sources.settings.entities.yuushya]
				ride_entity = true

			[light_sources.settings.entities.cobblemon]
				empty_pokeball = true
				pokemon = true

			[light_sources.settings.entities.travelersbackpack]
				backpack = true

			[light_sources.settings.entities.sit]
				entity_sit = true

