[Server]
	#Swim speed multiplier
	#Range: 1.0 ~ 10.0
	swimSpeedMultiplier = 2.0
	#Aqua affinity
	aquaAffinity = true
	#Night vision
	nightVision = true
	#Water breathing
	waterBreathing = true
